export const GESTURE = {
    EMA_ALPHA:          0.4,
    DEAD_ZONE:          0.004,
    CAMERA_SENSITIVITY: Math.PI,
    SCENE_WIDTH:        20.0,
    SCENE_HEIGHT:       15.0,
    OPEN_PALM_HOLD_MS:  200,
    CLOSED_FIST_HOLD_MS: 300,
    ZOOM_HOLD_MS:       200,
    ZOOM_COOLDOWN_MS:   300,
    MENU_HOLD_MS:       500,
    TWO_PALMS_HOLD_MS:  400,
    HAND_LOST_MS:       1000,
};

export const GESTURE_RAW = {
    NONE: 'NONE',
    OPEN_PALM: 'OPEN_PALM',
    CLOSED_FIST: 'CLOSED_FIST',
    ZOOM_OUT_GESTURE: 'ZOOM_OUT_GESTURE',
    ZOOM_IN_GESTURE: 'ZOOM_IN_GESTURE',
    ONE_FINGER: 'ONE_FINGER',
    TWO_FINGERS: 'TWO_FINGERS',
    THREE_FINGERS: 'THREE_FINGERS',
    FOUR_FINGERS: 'FOUR_FINGERS',
    THUMBS_UP: 'THUMBS_UP',
    THUMBS_DOWN: 'THUMBS_DOWN',
    LEFT_THREE_FINGERS: 'LEFT_THREE_FINGERS'
};

export const GESTURE_STATES = {
    IDLE: 'IDLE',
    CAMERA_MODE: 'CAMERA_MODE',
    OBJECT_MODE: 'OBJECT_MODE',
    ZOOM_OUT_MODE: 'ZOOM_OUT_MODE',
    ZOOM_IN_MODE: 'ZOOM_IN_MODE',
    MENU_MODE: 'MENU_MODE',
    SCALE_UP_MODE: 'SCALE_UP_MODE',
    SCALE_DOWN_MODE: 'SCALE_DOWN_MODE',
    ROTATION_MENU_MODE: 'ROTATION_MENU_MODE',
    ROTATION_ACTIVE_MODE: 'ROTATION_ACTIVE_MODE'
};
